[tool.poetry]
name = "prime-numbers"
version = "0.1.0"
description = ""
authors = ["Adam Smith <liversmiles@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
bitarray = "^2.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
